name: levcodes_dart
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  benchmark_harness: ^2.2.2
  path: ^1.8.0
  xml: ^6.3.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
